### ISSUE TITLE
Try to add invite only method 

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_commun_app#1]
Hi brother! I like commun app concept. Really good idea but my suggestion. Can you add invited users only can join in app or can post in app? Because you planned to help users to earn money via this app right? So unwanted users will come and will post spam so if we added invite only option it will make curiosity to use commun app  and also can avoid spam posts. Invite only method ->  https://github.com/fireship-io/invite-only-phone-auth

Just my suggestion, don't mind

**Comment by TheAlphamerc** [comment]
Yes, it makes sense to restrict users to posting spams. To avoid this I am gonna add some access level, restrictions and permissions to avoid this and can be changed by admin or moderator. While creating community admin/moderator can set access level like who can post or wether community is a open for everyone or user can join by invitation only.

**Comment by ublockme** [comment]
Nice.. all the best
