### ISSUE TITLE
sdk 2.12 / null safety?

### ISSUE THREAD

**Issue by jtkeyva** [TheAlphamerc/flutter_commun_app#5]
any plans for sdk 2.12 or supporting null safety? any specific reason you didn't start project with null safety?
thanks

**Comment by TheAlphamerc** [comment]
When I started the project I didn't have thought of starting with null safety. I'll update the flutter SDK constraints soon.

**Comment by jtkeyva** [comment]
Got it thanks. Was curious if people are still weary of null safety.
