### ISSUE TITLE
uid called on null

### ISSUE THREAD

**Issue by jtkeyva** [TheAlphamerc/flutter_commun_app#6]
seems to think i should be logged in, but i can't if i am running the app for the first time... any help appreciated.
thx

i'm getting:

```ssh
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mNoSuchMethodError: The getter 'uid' was called on null.<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mReceiver: null<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mTried calling: uid<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   Object.noSuchMethod (dart:core-patch/object_patch.dart:54:<…>
flutter: \^[[38;5;196m│ #1   AppCubit.checkAuthentication.<anonymous closure> (package:flutter_commun_app/cubit/app/app_cubit.dart:31:2<…>
flutter: \^[[38;5;196m│ #2   AppCubit.checkAuthentication.<anonymous closure> (package:flutter_commun_app/cubit/app/app_cubit.dart:29:<…>
flutter: \^[[38;5;196m│ #3   Right.fold (package:dartz/src/either.dart:189:6<…>
flutter: \^[[38;5;196m│ #4   AppCubit.checkAuthentication (package:flutter_commun_app/cubit/app/app_cubit.dart:23:1<…>
flutter: \^[[38;5;196m│ #5   <asynchronous suspensio<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ Log<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
`
```

**Comment by TheAlphamerc** [comment]
Have you set up the firebase correctly?

**Comment by jtkeyva** [comment]
I set it up like all my other projects, but not sure what your requirements are:

Enable Auth + Email + Twitter + Google
Create Firestore DB in test mode
Enable Storage

Is there anything else I need to do?

Thank you

**Comment by DEVSOG12** [comment]
@jtkeyva  I got the same error, I just when to `./lib/ui/app/commun_app.dart` edited home to be            
` home: const GetStartedPage(),`
Then it worked, it seems to be trying to fetch the user when the user has not been authenicated.

**Comment by jtkeyva** [comment]
@DEVSOG12 thanks but its still giving me the same error. do you mind sharing the full code for commun_app.dart and app_cubit.dart ?

**Comment by TheAlphamerc** [comment]
@jtkeyva the issue is fixed. Let me know if you face any other issue.

**Comment by DEVSOG12** [comment]
Thanks for the fix! Any milestones for the project. When would you implement remote config and notifications? :) 👍🏾

**Comment by TheAlphamerc** [comment]
Remote config and push notifications are on low priority right now. There are several other features and in line like community profile, community members and their permission, post edit/share/report/bookmark etc.

**Comment by jtkeyva** [comment]
Thanks a lot for the fix! Look forward to the updates.
