### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jtkeyva** [TheAlphamerc/flutter_commun_app#7]
Hey great job on this! I hope it gets as popular as your Flutter Twitter Clone :) I don't see any license on this repo and was wondering if you are actively developing or encouraging people to contribute to this?

Thanks
JT

**Comment by TheAlphamerc** [comment]
Hello @jtkeyva, Thanks for the appreciation. I'll add licence and a proper readme file in this project very soon. Now day's I am busy with other stuffs so didn't get time to work on this. I'll start work on this project once I am free.

**Comment by jtkeyva** [comment]
@TheAlphamerc thanks for the quick reply! Look forward to the license update and hope to be able to contribute at some point. Cheers!

**Comment by TheAlphamerc** [comment]
@jtkeyva, License is added. Feel free to contribute to project and create PR once sone.

**Comment by jtkeyva** [comment]
thanks @TheAlphamerc i'll see what i can do to contribute :)
