### ISSUE TITLE
all files ended with ".freezed.dart" got an error

### ISSUE THREAD

**Issue by dextermax3** [TheAlphamerc/flutter_commun_app#8]
@TheAlphamerc hello Sonu
i got below error once i open the project:
Target of URI hasn't been generated: 'post_model.g.dart'.
Try running the generator that will generate the file referenced by the URI.dart
( i tried flutter clean>>>>flutter pub get) but still not working

![commu app](https://user-images.githubusercontent.com/105817000/219759488-52dbb03a-10a5-41ed-883b-1a697ec5db40.jpg)

**Comment by TheAlphamerc** [comment]
@dextermax3  try running `flutter pub run build_runner build --delete-conflicting-outputs` command. It will generate all required files.

**Comment by dextermax3** [comment]
@TheAlphamerc Worked!
thank you :)
